# Generated by Django 3.2.5 on 2021-09-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='date_end_show',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='date_start_show',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='end_session_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='start_session_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
