# Generated by Django 3.2.5 on 2021-09-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20210922_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
