# Generated by Django 3.2.5 on 2021-09-27 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20210922_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hall',
            options={'verbose_name_plural': 'Halls'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_session', to='cinema.sessions'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='сonsumer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumer_purchase', to=settings.AUTH_USER_MODEL),
        ),
    ]
