# Generated by Django 3.2.5 on 2021-10-02 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_sessions_free_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='duration',
        ),
    ]
