# Generated by Django 3.2.5 on 2021-10-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_sessions_free_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='hall_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cinema.hall', verbose_name='Hall'),
        ),
    ]
