# Generated by Django 3.2.5 on 2021-10-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_alter_sessions_hall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='date_end_show',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='date_start_show',
            field=models.DateField(blank=True, null=True),
        ),
    ]
